#!/bin/bash
function join {
    local IFS="$1"
    shift
    echo "$*"
}

gradle="gradle.properties"
line=$(grep -n "modVersion" $gradle | cut -f 1 -d:)
prior=$(head -$((line-1)) $gradle)
posterior=$(tail -$((line+1)) $gradle)

version="$(grep -o "modVersion" $gradle | grep -Eom 1 "[0-9]+.[0-9]+.[0-9]+")"
echo "The current version is $version."

IFS="." read -ra version <<< "$version"
echo "Enter a version index."

while [ -z "$index" ]
do
    read -r index
    index=$(grep -Eo "[0-2]" <<< "$index" | head -1)
done

echo "Enter the new number for the version specified by this index."

while [ -z "$new" ]
do
    read -r new
    new=$(grep -Eo "[0-9]+" <<< "$new" | head -1)
done

if [ "$index" -le 1 ]
then
    version[2]="0"

    if [ "$index" == 0 ]
    then
        version[1]="0"
    fi
fi

version[$index]="$new"
new=$(join "." "${version[@]}")
echo "$prior" > $gradle
echo "modVersion = $new" >> $gradle
echo "$posterior" >> $gradle
echo "The new version is $new."
