#!/usr/bin/env python3
from re import search


def change_version(filename):
    with open(filename, 'r+') as file:
        lines = file.readlines()
        ver_expr = r'\d+\.\d+\.\d+'
        type_expr = r'(release|beta|alpha)'

        for i in range(len(lines)):
            line = lines[i]
            match = search(f'{ver_expr}-{type_expr}', line)

            if match:
                version = search(ver_expr, line)[0]
                before = line[:line.index(version)]
                after = line[line.index(version) + len(version):]
                version = version.split('.')

                print(f'\nThe current version in {filename} is {match[0]}.')

                index = None
                new = None

                while not index:
                    index = search(r'[0-2]', input('Enter the version index to change.\n'))

                    if index == '':
                        index = 2

                if index:
                    while not new:
                        new = search(r'\d+', input('Enter the new number for this index.\n'))
                else:
                    new = str(int(version[2]) + 1)

                version[int(index[0])] = new[0]
                line = f'{before}{".".join(version)}{after}'
                lines[i] = line
                file.seek(0)
                file.truncate()
                file.write(''.join(lines))
                break


change_version('build.gradle')
change_version('src/main/java/transfarmer/soulweapons/Main.java')
