modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/auoeke/soulbound-armory"
license = "GNU LGPL v3.0"

[[mods]]
modId = "soulboundarmory"
version = "0VERSION" # FML wants a leading digit here.
displayName = "soulbound armory"
description = "old Better Dungeons' soul weapons with additions"
