modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/auoeke/soulbound-armory"
license = "GNU LGPL v3.0"

[[mods]]
modId = "soulbound-armory"
version = "${file.jarVersion}"
displayName = "soulbound armory"
authors = "auoeke"
description = "old Better Dungeons' soul weapons with additions"
